# Prometheus configuration for South Delhi Real Estate monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Application monitoring
  - job_name: 'south-delhi-real-estate'
    scrape_interval: 30s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:5000']
    scrape_timeout: 10s

  # Node exporter for system metrics (if added)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # MySQL exporter for database metrics (if added)
  - job_name: 'mysql-exporter'
    static_configs:
      - targets: ['mysql-exporter:9104']

  # Nginx metrics (if nginx-prometheus-exporter is added)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  # Health check monitoring
  - job_name: 'health-checks'
    scrape_interval: 30s
    metrics_path: '/health'
    static_configs:
      - targets: ['app:5000']
    scrape_timeout: 5s 